import matplotlib.pyplot as plt
import numpy as np

plt.rcdefaults()
fig, ax = plt.subplots()
print("¿Qué tipo de datos vas a trabajar?")
data = input()
print("Metido.")
datos = ["1", "2", "3", "4", "5"]
print("Mete los datos 1:")
datos[0] = input()
print("Mete los datos 2:")
datos[1] = input()
print("Mete los datos 3:")
datos[2] = input()
print("Mete los datos 4:")
datos[3] = input()
print("Mete los datos 5:")
datos[4] = input()
cantidades = ["1", "2", "3", "4", "5"]
print("Mete las cantidades 1:")
cantidades[0] = input()
print("Mete las cantidades 2:")
cantidades[1] = input()
print("Mete las cantidades 3:")
cantidades[2] = input()
print("Mete las cantidades 4:")
cantidades[3] = input()
print("Mete las cantidades 5:")
cantidades[4] = input()
print("Todos los datos han metido")
print(cantidades)
print(datos)
print()

cantidad = [int(cantidades[0]), int(cantidades[1]), int(cantidades[2]), int(cantidades[3]), int(cantidades[4])]
ax.barh(datos, cantidad)
ax.set_facecolor('xkcd:salmon')
ax.legend([data])
fig.set_tight_layout({"pad": .2})
fig.patch.set_facecolor('#39768c')
fig.patch.set_alpha(0.7)
fig.savefig("Data1.png", facecolor=fig.get_facecolor(), edgecolor='none')
print("Nombre de la infografía:")
datosinfografia = input()
print("Metido")
print("Dirección del logo:")
logo = input()
print("Metido")
with open("infografia.html", "w") as archivo:
    archivo.write(datosinfografia)